### ISSUE TITLE
Comment issues with record formatting

### ISSUE THREAD

**Issue by jaspervdj** [haskell/stylish-haskell#273]
Here is a datatype with some comments:

```haskell
data Foo = Foo
   { -- | This is a comment above some line.
    -- It can span multiple lines.
     fooName :: String
   , fooAge :: Int
     -- ^ This is a comment below some line.
     -- It can span multiple lines.
   }
```

Here is what `stylish-haskell-0.10.0.0` produces:

```haskell
data Foo = Foo
    { fooName :: String
    , fooAge  :: Int
    -- ^ This is a comment below some line.
    }
```

**Comment by jaspervdj** [comment]
Related: #257

**Comment by lukasz-golebiewski** [comment]
This one is going to be very tricky to fix without resorting to https://hackage.haskell.org/package/haskell-src-exts-1.23.0/docs/Language-Haskell-Exts-Comments.html#v:associateHaddock. I'm currently thinking we should do the latter, but the consequence of that would be the fact that non-haddock comments are going to disappear (due to the nature of how `associateHaddock` works). @jaspervdj what do you think about this way forward?

**Comment by jaspervdj** [comment]
@lukasz-golebiewski Thanks a lot for looking into this!

I am fine with not supporting this but this means that:

1. `records` formatting can't be enabled by default (it isn't currently)
2. this should be called out in the documentation for record formatting 

I think there may be workarounds by dealing with the input directly and cross-referencing it with the AST.  But it's probably not worth doing so if we get the ghc-parser-lib port relatively soon.
